### ISSUE TITLE
Set upper bound for seed length

### ISSUE THREAD

**Issue by bbuchfink** [lucian-ilie/ALeS#1]
I'd like to use your tool to design seeds for Diamond (https://github.com/bbuchfink/diamond). For implementation purposes, it would be important for me to be able to set an upper bound for the seed length. So I would appreciate if this feature could be included.

**Comment by ArnabMallik** [comment]
Thanks for the issue request @bbuchfink. It sounds like a good and useful feature to have and would incorporate it in the next release, which is coming soon.

**Comment by ArnabMallik** [comment]
@bbuchfink the upper bound for seed length has been added in the latest release ALeS_1.5.
Please read README.md for instructions on running ALeS. Thanks.
